name: Build the theme (v3)

on:
  push:
    branches: [ 3.x-dev ]
  pull_request:
    branches: [ 3.x-dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECTROOT: app/design/frontend/Scandiweb/pwa
      FALLBACKROOT: vendor/scandipwa/source
    steps:
        
    - name: Get the scandipwa-base 3.x-dev
      uses: actions/checkout@v2.3.1
      with:
        # Repository name with owner. For example, actions/checkout
        repository: scandipwa/scandipwa-base
        ref: 3.x-dev
        path: .
    
    - name: Install the composer packages
      uses: php-actions/composer@v1
      with:
        command: install --ignore-platform-reqs

    - name: Setup Node.js
      uses: actions/setup-node@v2.1.0
      with:
        node-version: 10.19.0

    - name: Bootstrap the theme
      working-directory: src
      run: |
        cp -r $FALLBACKROOT/.github/bootstrapper/* .
        npm ci
        npm run bootstrap
        
    - name: Install themes dependencies
      run: |
        cd $PROJECTROOT
        npm ci

    - name: Build the theme
      run: |
        cd $PROJECTROOT
        npm run build
  
